version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: visitorisator-frontend-image
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: visitorisator-backend-image
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis:
    image: redis:latest
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    ports:
      - "6379:6379"
