version: "3"
services:
  redis:
    image: redis:latest

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: visitorisator-frontend-image
    depends_on:
      - backend
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: visitorisator-backend-image
    ports:
      - "3001:3001"
    depends_on:
      - redis
    environment:
      redis_server_addr: redis
    volumes:
      - ./backend:/app
