# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
  
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm i
      
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
      
      - name: Test frontend
        working-directory: ./frontend
        run: npm test

      - name: Create frontend Build Directory
        run: mkdir -p ./frontend/build/
      
      - name: Upload Frontend Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: visitorisator-frontend-build
          path: ./frontend/build/
      
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm i
  
      - name: Test backend
        working-directory: ./backend
        run: npm test
